on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      create_pkg_config_version:
        required: false
        type: string
      fix_xlocale:
        required: false
        type: boolean

jobs:
  reusable_defined_icu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.34'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - run: apt remove -y libicu-dev
      - name: perl -V
        run: perl -V
      - name: Supply xlocale.h
        if: ${{ inputs.fix_xlocale }}
        run: '[ -e /usr/include/xlocale.h ] || ln -s locale.h /usr/include/xlocale.h'
      - name: Download ICU
        run: curl -L ${{ inputs.url }} > icu.tar.gz
      - name: Build & install ICU
        run: tar -xzf icu.tar.gz && cd icu/source && ./configure --prefix=$PWD/../build && make install
      - name: Create pkg-config file if needed
        if: ${{ inputs.create_pkg_config_version }}
        run: |
            mkdir icu/build/lib/pkgconfig && perl -MCwd -E'my $pwd = Cwd::getcwd; $, = "\n"; say q<Name: icu>, q<Version: ${{ inputs.create_pkg_config_version }}>, q<Description: icu>, qq<Cflags: -I$pwd/icu/build/include>, qq<Libs: -L$pwd/icu/build/lib -licui18n -licuio -licuuc -licudata>' > icu/build/lib/pkgconfig/icu.pc
      - name: Install Perl Dependencies
        run: cpanm --notest --installdeps --with-configure --with-develop .
      - name: perl Makefile.PL
        run: perl Makefile.PL
        env:
            PKG_CONFIG_PATH: icu/build/lib/pkgconfig
      - name: make
        run: make
      - name: Run Tests
        run: prove -wlvmb t
